/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Form.Customer_Form;

/**
 *
 * @author Admin
 */
public class AboutUs_Form extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs_Form
     */
    public AboutUs_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new View.Swing.PanelRound();
        img = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        footer = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMember = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        header1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 222, 222));

        panelRound1.setBackground(new java.awt.Color(247, 247, 247));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/aboutus.jpg"))); // NOI18N

        header.setFont(new java.awt.Font("Papyrus", 1, 20)); // NOI18N
        header.setForeground(new java.awt.Color(108, 91, 123));
        header.setText("ABOUT US");

        wel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        wel.setForeground(new java.awt.Color(63, 63, 63));
        wel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wel.setText("<html>  Welcome to  <i style=\"color:rgb(108,91,123);font-size:16px;\">  ROYAL THEDREAMERS<i> </html>");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt.setEditable(false);
        txt.setBackground(new java.awt.Color(255, 255, 255));
        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(89, 89, 89));
        txt.setLineWrap(true);
        txt.setRows(5);
        txt.setText("Chào mừng quý khách đến với Restaurant - biểu tượng của sự sang trọng và tinh tế trong nghệ thuật ẩm thực. Tọa lạc tại trái tim của thành phố, Restaurant không chỉ là một nhà hàng 5 sao, mà còn là điểm đến của những trải nghiệm ẩm thực đẳng cấp quốc tế.\r\n" + //
                        "\r\n" + //
                        "Khi bước qua cánh cửa của Restaurant, quý khách sẽ lập tức cảm nhận được không gian trang nhã và lịch lãm, nơi mỗi chi tiết đều được chăm chút tỉ mỉ. Ánh đèn vàng dịu nhẹ, âm nhạc du dương, cùng với hương thơm quyến rũ từ những món ăn tinh tế, tất cả hòa quyện tạo nên một bản giao hưởng ẩm thực khó quên.\r\n" + //
                        "\r\n" + //
                        "Đội ngũ đầu bếp của chúng tôi là những nghệ nhân ẩm thực hàng đầu, đã trải qua quá trình lựa chọn khắt khe và đào tạo bài bản. Họ là những người thợ thực sự của hương vị, luôn tìm tòi và sáng tạo không ngừng để mang đến những món ăn độc đáo, phản ánh sự phong phú của các nền văn hóa ẩm thực trên thế giới.\r\n" + //
                        "\r\n" + //
                        "Thực đơn của Restaurant là sự kết hợp hoàn hảo giữa truyền thống và hiện đại, giữa địa phương và quốc tế. Mỗi món ăn đều là kết quả của quá trình tuyển chọn nguyên liệu tươi ngon nhất, được nhập khẩu từ những vùng đất nổi tiếng với sản phẩm chất lượng cao. Chúng tôi tự hào mang đến cho thực khách những hương vị đích thực và không gian ẩm thực đẳng cấp.\r\n" + //
                        "\r\n" + //
                        "Không chỉ là nhà hàng, Restaurant còn là nơi tổ chức các sự kiện quan trọng, từ những buổi tiệc tối sang trọng cho đến các hội nghị, hội thảo cấp cao. Với không gian linh hoạt và dịch vụ chuyên nghiệp, chúng tôi cam kết mang đến sự kiện của bạn sự hoàn hảo và ấn tượng không thể nào quên.\r\n" + //
                        "\r\n" + //
                        "Sự hài lòng của thực khách là ưu tiên hàng đầu của chúng tôi. Đội ngũ nhân viên chuyên nghiệp, thân thiện và chu đáo sẽ đảm bảo mỗi khách hàng đều nhận được sự chăm sóc tận tình và dịch vụ cá nhân hóa, từng bước, từng khoảnh khắc tại Restaurant.\r\n" + //
                        "\r\n" + //
                        "Hãy để Restaurant trở thành điểm đến yêu thích của bạn, nơi mỗi bữa ăn không chỉ là việc thưởng thức ẩm thực, mà còn là hành trình khám phá và trải nghiệm. Chúng tôi mong chờ được chào đón quý khách và mang đến những giây phút thăng hoa trong thế giới ẩm thực đỉnh cao.\r\n" + //
                        "\r\n" + //
                        "Restaurant - Nơi hương vị và phong cách hội tụ, tạo nên những kỷ niệm không thể phai mờ. Chúng tôi tin tưởng rằng, mỗi lần ghé thăm, quý khách sẽ lại phát hiện thêm những điều mới mẻ và thú vị, làm giàu thêm cuộc sống của mình qua từng món ăn, từng dịch vụ tại đây. Xin cảm ơn và hân hạnh được phục vụ!");
        txt.setWrapStyleWord(true);
        txt.setBorder(null);
        txt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt.setFocusable(false);
        txt.setRequestFocusEnabled(false);
        txt.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(txt);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        footer.setForeground(new java.awt.Color(63, 63, 63));
        footer.setText("2024 - ĐỀ TÀI QUẢN LÝ ĐẶT BÀN NHÀ HÀNG by NhÓM 8");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFocusable(false);

        listMember.setColumns(20);
        listMember.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        listMember.setForeground(new java.awt.Color(89, 89, 89));
        listMember.setRows(5);
        listMember.setText("Team Members :\n Phạm Xuân Hùng - 21133971 - Leader\nPhạm Nguyễn Tấn Kiệt - 20124081 \n ");
        listMember.setBorder(null);
        listMember.setFocusable(false);
        jScrollPane3.setViewportView(listMember);

        jSeparator1.setBackground(new java.awt.Color(76, 76, 76));

        header1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        header1.setForeground(new java.awt.Color(89, 89, 89));
        header1.setText("Tastes like a bit of heaven on your tongue.");
        header1.setToolTipText("");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(header))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(footer)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                                .addComponent(header1)
                                .addGap(116, 116, 116)))))
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea listMember;
    private View.Swing.PanelRound panelRound1;
    private javax.swing.JTextArea txt;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
